from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render
from . import read

def index(request):
	context = {
		'jawa_pos_01' : read.jawa_pos_01,
		'jawa_neg_01' : read.jawa_neg_01,
		'sumatera_pos_01' : read.sumatera_pos_01,
		'sumatera_neg_01' : read.sumatera_neg_01,
		'sulawesi_pos_01' : read.sulawesi_pos_01,
		'sulawesi_neg_01' : read.sulawesi_neg_01,
		'kalimantan_pos_01' : read.kalimantan_pos_01,
		'kalimantan_neg_01' : read.kalimantan_neg_01,
		'kep_maluku_pos_01' : read.kep_maluku_pos_01,
		'kep_maluku_neg_01' : read.kep_maluku_neg_01,
		'kep_nusa_pos_01' : read.kep_nusa_pos_01,
		'kep_nusa_neg_01' : read.kep_nusa_neg_01,
		'papua_pos_01' : read.papua_pos_01,
		'papua_neg_01' : read.papua_neg_01,
		'debat1_01' : read.debat1_01,
		'debat2_01' : read.debat2_01,
		'debat3_01' : read.debat3_01,
		'debat4_01' : read.debat4_01,
		'debat5_01' : read.debat5_01,
		'jumlah_01' : read.jumlah_01,
		'positif_01' : read.positif_01,
		'negatif_01' : read.negatif_01,
		'positif_persen_01':read.positif_persen_01,
		'negatif_persen_01':read.negatif_persen_01,
		'jawa_pos_02' : read.jawa_pos_02,
		'jawa_neg_02' : read.jawa_neg_02,
		'sumatera_pos_02' : read.sumatera_pos_02,
		'sumatera_neg_02' : read.sumatera_neg_02,
		'sulawesi_pos_02' : read.sulawesi_pos_02,
		'sulawesi_neg_02' : read.sulawesi_neg_02,
		'kalimantan_pos_02' : read.kalimantan_pos_02,
		'kalimantan_neg_02' : read.kalimantan_neg_02,
		'kep_maluku_pos_02' : read.kep_maluku_pos_02,
		'kep_maluku_neg_02' : read.kep_maluku_neg_02,
		'kep_nusa_pos_02' : read.kep_nusa_pos_02,
		'kep_nusa_neg_02' : read.kep_nusa_neg_02,
		'papua_pos_02' : read.papua_pos_02,
		'papua_neg_02' : read.papua_neg_02,
		'jumlah_02' : read.jumlah_02,
		'positif_02' : read.positif_02,
		'negatif_02' : read.negatif_02,
		'positif_persen_02':read.positif_persen_02,
		'negatif_persen_02':read.negatif_persen_02,

		'indo_pre_01':read.indo_pre_01,
		'jawa_pre_01':read.jawa_pre_01,
		'sumatera_pre_01':read.sumatera_pre_01,
		'sulawesi_pre_01':read.sulawesi_pre_01,
		'kalimantan_pre_01':read.kalimantan_pre_01,
		'kep_maluku_pre_01':read.kep_maluku_pre_01,
		'kep_nusa_pre_01':read.kep_nusa_pre_01,
		'papua_pre_01':read.papua_pre_01,
		'indo_pasca_01':read.indo_pasca_01,
		'jawa_pasca_01':read.jawa_pasca_01,
		'sumatera_pre_01':read.sumatera_pasca_01,
		'sulawesi_pasca_01':read.sulawesi_pasca_01,
		'kalimantan_pasca_01':read.kalimantan_pasca_01,
		'kep_maluku_pasca_01':read.kep_maluku_pasca_01,
		'kep_nusa_pasca_01':read.kep_nusa_pasca_01,
		'papua_pasca_01':read.papua_pasca_01,

		'indo_pre_02':read.indo_pre_02,
		'jawa_pre_02':read.jawa_pre_02,
		'sumatera_pre_02':read.sumatera_pre_02,
		'sulawesi_pre_02':read.sulawesi_pre_02,
		'kalimantan_pre_02':read.kalimantan_pre_02,
		'kep_maluku_pre_02':read.kep_maluku_pre_02,
		'kep_nusa_pre_02':read.kep_nusa_pre_02,
		'papua_pre_02':read.papua_pre_02,
		'indo_pasca_02':read.indo_pasca_02,
		'jawa_pasca_02':read.jawa_pasca_02,
		'sumatera_pasca_02':read.sumatera_pasca_02,
		'sulawesi_pasca_02':read.sulawesi_pasca_02,
		'kalimantan_pasca_02':read.kalimantan_pasca_02,
		'kep_maluku_pasca_02':read.kep_maluku_pasca_02,
		'kep_nusa_pasca_02':read.kep_nusa_pasca_02,
		'papua_pasca_02':read.papua_pasca_02,

		'indo_pre_pos_01' : round(read.indo_pre_pos_01,2),
		'jawa_pre_pos_01':round(read.jawa_pre_pos_01,2),
		'sumatera_pre_pos_01':round(read.sumatera_pre_pos_01,2),
		'sulawesi_pre_pos_01':round(read.sulawesi_pre_pos_01,2),
		'kalimantan_pre_pos_01':round(read.kalimantan_pre_pos_01,2),
		'kep_maluku_pre_pos_01':round(read.kep_maluku_pre_pos_01,2),
		'kep_nusa_pre_pos_01':round(read.kep_nusa_pre_pos_01,2),
		'papua_pre_pos_01':round(read.papua_pre_pos_01,2),
		'indo_pasca_pos_01' : round(read.indo_pasca_pos_01,2),
		'jawa_pasca_pos_01':round(read.jawa_pasca_pos_01,2),
		'sumatera_pasca_pos_01':round(read.sumatera_pasca_pos_01,2),
		'sulawesi_pasca_pos_01':round(read.sulawesi_pasca_pos_01,2),
		'kalimantan_pasca_pos_01':round(read.kalimantan_pasca_pos_01,2),
		'kep_maluku_pasca_pos_01':round(read.kep_maluku_pasca_pos_01,2),
		'kep_nusa_pasca_pos_01':round(read.kep_nusa_pasca_pos_01,2),
		'papua_pasca_pos_01':round(read.papua_pasca_pos_01,2),

		'debat1_pos_01':round(read.debat1_pos_01,2),
		'debat2_pos_01':round(read.debat2_pos_01,2),
		'debat3_pos_01':round(read.debat3_pos_01,2),
		'debat4_pos_01':round(read.debat4_pos_01,2),
		'debat5_pos_01':round(read.debat5_pos_01,2),
		'debat1_neg_01':round(read.debat1_neg_01,2),
		'debat2_neg_01':round(read.debat2_neg_01,2),
		'debat3_neg_01':round(read.debat3_neg_01,2),
		'debat4_neg_01':round(read.debat4_neg_01,2),
		'debat5_neg_01':round(read.debat5_neg_01,2),

		'debat1_02' : read.debat1_02,
		'debat2_02' : read.debat2_02,
		'debat3_02' : read.debat3_02,
		'debat4_02' : read.debat4_02,
		'debat5_02' : read.debat5_02,
		'debat1_pos_02':round(read.debat1_pos_02,2),
		'debat2_pos_02':round(read.debat2_pos_02,2),
		'debat3_pos_02':round(read.debat3_pos_02,2),
		'debat4_pos_02':round(read.debat4_pos_02,2),
		'debat5_pos_02':round(read.debat5_pos_02,2),
		'debat1_neg_02':round(read.debat1_neg_02,2),
		'debat2_neg_02':round(read.debat2_neg_02,2),
		'debat3_neg_02':round(read.debat3_neg_02,2),
		'debat4_neg_02':round(read.debat4_neg_02,2),
		'debat5_neg_02':round(read.debat5_neg_02,2),
		'indo_pre_pos_02':round(read.indo_pre_pos_02,2),
		'jawa_pre_pos_02':round(read.jawa_pre_pos_02,2),
		'sumatera_pre_pos_02':round(read.sumatera_pre_pos_02,2),
		'sulawesi_pre_pos_02':round(read.sulawesi_pre_pos_02,2),
		'kalimantan_pre_pos_02':round(read.kalimantan_pre_pos_02,2),
		'kep_maluku_pre_pos_02':round(read.kep_maluku_pre_pos_02,2),
		'kep_nusa_pre_pos_02':round(read.kep_nusa_pre_pos_02,2),
		'papua_pre_pos_02':round(read.papua_pre_pos_02,2),
		'indo_pasca_pos_02':round(read.indo_pasca_pos_02,2),
		'jawa_pasca_pos_02':round(read.jawa_pasca_pos_02,2),
		'sumatera_pasca_pos_02':round(read.sumatera_pasca_pos_02,2),
		'sulawesi_pasca_pos_02':round(read.sulawesi_pasca_pos_02,2),
		'kalimantan_pasca_pos_02':round(read.kalimantan_pasca_pos_02,2),
		'kep_maluku_pasca_pos_02':round(read.kep_maluku_pasca_pos_02,2),
		'kep_nusa_pasca_pos_02':round(read.kep_nusa_pasca_pos_02,2),
		'papua_pasca_pos_02':round(read.papua_pasca_pos_02,2),

		'indo_pre_neg_01':round(read.indo_pre_neg_01,2),
		'jawa_pre_neg_01':round(read.jawa_pre_neg_01,2),
		'sumatera_pre_neg_01':round(read.sumatera_pre_neg_01,2),
		'sulawesi_pre_neg_01':round(read.sulawesi_pre_neg_01,2),
		'kalimantan_pre_neg_01':round(read.kalimantan_pre_neg_01,2),
		'kep_maluku_pre_neg_01':round(read.kep_maluku_pre_neg_01,2),
		'kep_nusa_pre_neg_01':round(read.kep_nusa_pre_neg_01,2),
		'papua_pre_neg_01':round(read.papua_pre_neg_01,2),
		'indo_pasca_neg_01':round(read.indo_pasca_neg_01,2),
		'jawa_pasca_neg_01':round(read.jawa_pasca_neg_01,2),
		'sumatera_pasca_neg_01':round(read.sumatera_pasca_neg_01,2),
		'sulawesi_pasca_neg_01':round(read.sulawesi_pasca_neg_01,2),
		'kalimantan_pasca_neg_01':round(read.kalimantan_pasca_neg_01,2),
		'kep_maluku_pasca_neg_01':round(read.kep_maluku_pasca_neg_01,2),
		'kep_nusa_pasca_neg_01':round(read.kep_nusa_pasca_neg_01,2),
		'papua_pasca_neg_01':round(read.papua_pasca_neg_01,2),

		'indo_pre_neg_02':round(read.indo_pre_neg_02,2),
		'jawa_pre_neg_02':round(read.jawa_pre_neg_02,2),
		'sumatera_pre_neg_02':round(read.sumatera_pre_neg_02,2),
		'sulawesi_pre_neg_02':round(read.sulawesi_pre_neg_02,2),
		'kalimantan_pre_neg_02':round(read.kalimantan_pre_neg_02,2),
		'kep_maluku_pre_neg_02':round(read.kep_maluku_pre_neg_02,2),
		'kep_nusa_pre_neg_02':round(read.kep_nusa_pre_neg_02,2),
		'papua_pre_neg_02':round(read.papua_pre_neg_02,2),
		'indo_pasca_neg_02':round(read.indo_pasca_neg_02,2),
		'jawa_pasca_neg_02':round(read.jawa_pasca_neg_02,2),
		'sumatera_pasca_neg_02':round(read.sumatera_pasca_neg_02,2),
		'sulawesi_pasca_neg_02':round(read.sulawesi_pasca_neg_02,2),
		'kalimantan_pasca_neg_02':round(read.kalimantan_pasca_neg_02,2),
		'kep_maluku_pasca_neg_02':round(read.kep_maluku_pasca_neg_02,2),
		'kep_nusa_pasca_neg_02':round(read.kep_nusa_pasca_neg_02,2),
		'papua_pasca_neg_02':round(read.papua_pasca_neg_02,2),

		'jumlah' : read.jumlah,
		'positif' : read.positif,
		'negatif' : read.negatif,
		'jumlah_jawa_01':read.jumlah_jawa_01,
		'jumlah_jawa_02':read.jumlah_jawa_02,
		'jumlah_sumatera_01':read.jumlah_sumatera_01,
		'jumlah_sumatera_02':read.jumlah_sumatera_02,
		'jumlah_sulawesi_01':read.jumlah_sulawesi_01,
		'jumlah_sulawesi_02':read.jumlah_sulawesi_02,
		'jumlah_kalimantan_01':read.jumlah_kalimantan_01,
		'jumlah_kalimantan_02':read.jumlah_kalimantan_02,
		'jumlah_kep_maluku_01':read.jumlah_kep_maluku_01,
		'jumlah_kep_maluku_02':read.jumlah_kep_maluku_02,
		'jumlah_kep_nusa_01':read.jumlah_kep_nusa_01,
		'jumlah_kep_nusa_02':read.jumlah_kep_nusa_02,
		'jumlah_papua_01':read.jumlah_papua_01,
		'jumlah_papua_02':read.jumlah_papua_02,
		'jawa_pos_persen_01':round(read.jawa_pos_persen_01,2),
		'kalimantan_pos_persen_01':round(read.kalimantan_pos_persen_01,2),
		'kep_maluku_pos_persen_01':round(read.kep_maluku_pos_persen_01,2),
		'kep_nusa_pos_persen_01':round(read.kep_nusa_pos_persen_01,2),
		'papua_pos_persen_01':round(read.papua_pos_persen_01,2),
		'sumatera_pos_persen_01':round(read.sumatera_pos_persen_01,2),
		'sulawesi_pos_persen_01':round(read.sulawesi_pos_persen_01,2),
		'jawa_pos_persen_02':round(read.jawa_pos_persen_02,2),
		'kalimantan_pos_persen_02':round(read.kalimantan_pos_persen_02,2),
		'kep_maluku_pos_persen_02':round(read.kep_maluku_pos_persen_02,2),
		'kep_nusa_pos_persen_02':round(read.kep_nusa_pos_persen_02,2),
		'papua_pos_persen_02':round(read.papua_pos_persen_02,2),
		'sumatera_pos_persen_02':round(read.sumatera_pos_persen_02,2),
		'sulawesi_pos_persen_02':round(read.sulawesi_pos_persen_02,2),
		'jawa_neg_persen_01': round(read.jawa_neg_persen_01,2),
		'kalimantan_neg_persen_01':round(read.kalimantan_neg_persen_01,2),
		'kep_maluku_neg_persen_01':round(read.kep_maluku_neg_persen_01,2),
		'kep_nusa_neg_persen_01':round(read.kep_nusa_neg_persen_01,2),
		'papua_neg_persen_01':round(read.papua_neg_persen_01,2),
		'sumatera_neg_persen_01':round(read.sumatera_neg_persen_01,2),
		'sulawesi_neg_persen_01':round(read.sulawesi_neg_persen_01,2),
		'jawa_neg_persen_02':round(read.jawa_neg_persen_02,2),
		'kalimantan_neg_persen_02':round(read.kalimantan_neg_persen_02,2),
		'kep_maluku_neg_persen_02':round(read.kep_maluku_neg_persen_02,2),
		'kep_nusa_neg_persen_02':round(read.kep_nusa_neg_persen_02,2),
		'papua_neg_persen_02':round(read.papua_neg_persen_02,2),
		'sumatera_neg_persen_02':round(read.sumatera_neg_persen_02,2),
		'sulawesi_neg_persen_02':round(read.sulawesi_neg_persen_02,2),
		'text':'Data diambil pada bulan Januari - Mei 2019',
		# 'indo_pos_persen_01':round(read.indo_pos_persen_01,2),
		# 'indo_neg_persen_01':round(read.indo_neg_persen_01,2),
		# 'indo_pos_persen_02':round(read.indo_pos_persen_02,2),
		# 'indo_neg_persen_02':round(read.indo_neg_persen_02,2),
	}
	return render(request,'dashboard.html', context)

def index02(request):
	context = {
		'jumlah_02' : read.jumlah_02,
		'positif_02' : read.positif_02,
		'negatif_02' : read.negatif_02,
		'positif_persen_02':round(read.positif_persen_02,2),
		'negatif_persen_02':round(read.negatif_persen_02,2),
	}
	return render(request,'prabowo.html', context)

def index01(request):
	context = {
		'jumlah_01' : read.jumlah_01,
		'positif_01' : read.positif_01,
		'negatif_01' : read.negatif_01,
		'positif_persen_01':round(read.positif_persen_01,2),
		'negatif_persen_01':round(read.negatif_persen_01,2),
	}
	return render(request,'jokowi.html', context)

